import Image from "next/image";
import Link from "next/link";
import { ArrowRight, BadgeCheck, Boxes, CheckCircle2, Factory, Globe2, ShieldCheck } from "lucide-react";
import { products, industries } from "@/data/site";
import { ProductVisual } from "@/components/ProductVisual";
import { CTA } from "@/components/CTA";

export default function Home() {
  return <>
    <section className="relative min-h-[620px] overflow-hidden bg-navy text-white">
      <Image src="/images/valve-hero.png" alt="Ductile iron valves in a waterworks facility" fill priority sizes="100vw" className="object-cover object-center opacity-55" />
      <div className="absolute inset-0 bg-gradient-to-r from-navy via-navy/85 to-navy/15" />
      <div className="grid-lines absolute inset-0" />
      <div className="relative mx-auto flex min-h-[620px] max-w-7xl items-center px-5 py-20">
        <div className="max-w-4xl"><div className="mb-6 inline-flex items-center gap-2 border border-white/25 bg-white/10 px-4 py-2 text-xs font-bold uppercase tracking-[.2em]"><span className="h-2 w-2 bg-signal"/>Ductile Iron Valve Specialist</div>
          <h1 className="text-5xl font-black leading-[1.05] md:text-7xl">Metal Seated Gate Valves<br/><span className="text-blue-300"> & Double Eccentric Butterfly Valves</span></h1>
          <p className="mt-6 max-w-3xl border-l-4 border-signal pl-5 text-lg leading-8 text-white/80 md:text-xl">Ductile iron valve solutions for waterworks, municipal infrastructure, and international project supply.</p>
          <div className="mt-9 flex flex-wrap gap-3"><Link href="/products" className="bg-signal px-7 py-4 text-sm font-bold uppercase tracking-wider">Explore Products</Link><Link href="/contact" className="border border-white/40 bg-white/10 px-7 py-4 text-sm font-bold uppercase tracking-wider">Request a Quote</Link></div>
        </div>
      </div>
    </section>
    <section className="border-b border-slate-200 bg-white"><div className="mx-auto grid max-w-7xl grid-cols-2 md:grid-cols-4">{[[BadgeCheck,"Ductile iron valve focus"],[Globe2,"International B2B supply"],[Boxes,"Waterworks project packages"],[ShieldCheck,"Quality-oriented sourcing"]].map(([Icon,label],i)=><div key={label as string} className={`flex items-center gap-3 border-slate-200 px-5 py-6 ${i<3?"md:border-r":""}`}><Icon className="text-valve"/><span className="text-sm font-bold text-navy">{label as string}</span></div>)}</div></section>
    <section className="px-5 py-20"><div className="mx-auto max-w-7xl"><div className="mb-10 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow">Primary product focus</p><h2 className="section-title">Two core ductile iron valve ranges<br/> for water infrastructure.</h2></div><Link href="/products" className="flex items-center gap-2 text-sm font-bold text-valve">View complete product range <ArrowRight size={16}/></Link></div>
      <div className="grid gap-6 md:grid-cols-2">{products.slice(0,2).map(p=><Link href={`/products/${p.slug}`} key={p.slug} className="group overflow-hidden border border-slate-200 bg-white shadow-sm hover:border-valve hover:shadow-xl"><ProductVisual type={p.type} image={p.image} name={p.name} compact/><div className="p-7"><span className="text-[10px] font-bold uppercase tracking-widest text-signal">Core ductile iron product</span><h3 className="mt-2 text-2xl font-black text-navy group-hover:text-valve">{p.name}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{p.short}</p><span className="mt-5 flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-valve">View product series <ArrowRight size={14}/></span></div></Link>)}</div></div></section>
    <section className="bg-mist px-5 py-20"><div className="mx-auto grid max-w-7xl gap-12 lg:grid-cols-2 lg:items-center"><div><p className="eyebrow">Established supply capability</p><h2 className="section-title">Ductile iron expertise backed by broader project supply.</h2><p className="mt-6 leading-8 text-slate-600">Established in the early 1990s, Dalian Dawei combines international supply experience with a focused product direction. Metal seated gate valves and flanged double eccentric butterfly valves lead our offering, while other valves and piping products remain available for complete project packages.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{["BS and DIN waterworks valve options","North America, Europe, Middle East and Asia","Flexible sourcing and consolidation","Export-ready coordination"].map(x=><div className="flex gap-2 text-sm font-bold text-navy" key={x}><CheckCircle2 size={18} className="shrink-0 text-signal"/>{x}</div>)}</div></div><div className="grid grid-cols-2 gap-4"><div className="bg-navy p-7 text-white"><Factory size={34} className="text-signal"/><b className="mt-12 block text-3xl">Ductile Iron</b><p className="mt-2 text-sm leading-6 text-white/60">Core valve focus for waterworks and infrastructure.</p></div><div className="mt-10 bg-valve p-7 text-white"><Globe2 size={34} className="text-blue-200"/><b className="mt-12 block text-3xl">Since 1990s</b><p className="mt-2 text-sm leading-6 text-white/70">International industrial supply experience.</p></div></div></div></section>
    <section className="px-5 py-20"><div className="mx-auto max-w-7xl"><div className="mb-10"><p className="eyebrow">Industries & applications</p><h2 className="section-title">Built around where valves work.</h2></div><div className="grid gap-px overflow-hidden border bg-slate-200 md:grid-cols-5">{industries.map(([name,desc],i)=><div className="bg-white p-6" key={name}><span className="text-4xl font-black text-slate-200">0{i+1}</span><h3 className="mt-8 font-black text-navy">{name}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{desc}</p></div>)}</div></div></section>
    <CTA />
  </>;
}
