import Image from "next/image";
import { ClipboardCheck, FileCheck2, PackageCheck, SearchCheck } from "lucide-react";
import { PageHero } from "@/components/PageHero";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Card, CardContent } from "@/components/ui/card";

export const metadata={title:"Quality & Certifications",description:"Quality assurance from requirement review to export coordination, with manufacturing partners holding ISO 9001, API 6D, and CE/PED certifications."};

export default function Quality(){
  const steps=[[SearchCheck,"Requirement Review","Specifications, standards, materials, and documentation are clarified before supply."],[ClipboardCheck,"Inspection & Testing","Appearance, dimensions, corrosion protection, operation, shell, and seat tests are coordinated as required."],[FileCheck2,"Documentation","Available certificates, drawings, inspection documents, and packing details are organized for the order."],[PackageCheck,"Export Coordination","Marking, packing, and shipment preparation are aligned with international delivery needs."]];
  const certs=[["certification_1.png","ISO 9001"],["certification_2.png","API 6D"],["certification_3.png","CE / PED"],["certification_4.png","Fire Safe Test"]];
  return <><PageHero eyebrow="Quality assurance system" title="Confidence from inquiry to shipment." description="Quality has always been a top priority. Products are designed, manufactured, inspected, and tested against international standards and customer-specific requirements."/><section className="px-5 py-20"><div className="mx-auto max-w-7xl"><div className="grid gap-6 md:grid-cols-2">{steps.map(([Icon,n,d])=><Card key={n as string}><CardContent className="p-8"><Icon className="text-primary" size={34}/><h2 className="mt-6 text-xl font-black text-navy">{n as string}</h2><p className="mt-3 leading-7 text-muted-foreground">{d as string}</p></CardContent></Card>)}</div><div className="mt-16"><p className="eyebrow">Certifications</p><h2 className="section-title">Industry certification capability.</h2><div className="mt-8 grid grid-cols-2 gap-5 md:grid-cols-4">{certs.map(([file,label])=><Card className="bg-muted p-4 text-center" key={file}><div className="relative h-56"><Image src={`/images/original/quality/${file}`} alt={label} fill sizes="(min-width: 768px) 25vw, 50vw" className="object-contain"/></div><b className="mt-3 block text-sm text-navy">{label}</b></Card>)}</div></div><div className="mt-16"><p className="eyebrow">Processing & testing</p><div className="grid grid-cols-2 gap-4 md:grid-cols-4">{["qualityimg_4.png","qualityimg_5.png","qualityimg_6.png","qualityimg_7.png","qualityimg_8.png","qualityimg_9.png","qualityimg_10.png"].map(file=><Card className="relative h-40 overflow-hidden bg-muted" key={file}><Image src={`/images/original/quality/${file}`} alt="Dawei quality control facility" fill sizes="(min-width: 768px) 25vw, 50vw" className="object-cover"/></Card>)}</div></div><Alert variant="warning" className="mt-8"><AlertTitle>Certification Scope</AlertTitle><AlertDescription>Certification scope and availability vary by product and manufacturing partner. Please include required certificates and standards in your inquiry.</AlertDescription></Alert></div></section></>;
}
