import Link from "next/link";
import { products } from "@/data/site";
import { ProductVisual } from "@/components/ProductVisual";
import { ArrowRight } from "lucide-react";
import { CTA } from "@/components/CTA";
import catalog from "@/data/legacy-catalog.json";
import { CatalogExplorer } from "@/components/CatalogExplorer";
export const metadata = { title: "Products" };
export default function Products(){return <><section className="bg-navy px-5 py-20 text-white"><div className="mx-auto max-w-7xl"><p className="eyebrow !text-blue-300">Product center</p><h1 className="max-w-5xl text-5xl font-black">Ductile Iron Valves for Waterworks</h1><p className="mt-5 max-w-3xl leading-8 text-white/65">Our primary focus is metal seated gate valves and flanged double eccentric butterfly valves. A broader historical valve and piping range remains available for project requirements.</p><div className="mt-8 flex flex-wrap gap-8 text-sm"><p><b className="text-2xl text-signal">Metal Seated Gate Valves</b><br/>Core isolation valve range</p><p><b className="text-2xl text-signal">Double Eccentric Butterfly Valves</b><br/>Core flanged flow-control range</p></div></div></section><section className="px-5 py-16"><div className="mx-auto max-w-7xl"><div className="mb-10"><p className="eyebrow">Product categories</p><h2 className="section-title">Core products first, broader capabilities available.</h2></div><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{products.map((p,i)=><Link href={`/products/${p.slug}`} key={p.slug} className={`group overflow-hidden border border-slate-200 hover:border-valve hover:shadow-xl ${i<2?"lg:col-span-1 ring-2 ring-valve/20":""}`}><ProductVisual type={p.type} image={p.image} name={p.name} compact/><div className="p-6">{i<2&&<span className="mb-2 block text-[10px] font-bold uppercase tracking-widest text-signal">Primary product focus</span>}<h2 className="text-xl font-black text-navy group-hover:text-valve">{p.name}</h2><p className="mt-3 text-sm leading-6 text-slate-500">{p.short}</p><span className="mt-5 flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-valve">Explore category <ArrowRight size={14}/></span></div></Link>)}</div></div></section><section className="border-t bg-mist px-5 py-16"><div className="mx-auto max-w-7xl"><div className="mb-10"><p className="eyebrow">Complete archive range</p><h2 className="section-title">Detailed product selection.</h2><p className="mt-4 max-w-3xl leading-7 text-slate-600">Core ductile iron products appear first. Search the complete historical range by product type, material, standard, or pressure class for broader project requirements.</p></div><CatalogExplorer products={catalog}/></div></section><CTA/></>}
