import Link from "next/link";
import { products } from "@/data/site";
import { ProductVisual } from "@/components/ProductVisual";
import { ArrowRight } from "lucide-react";
import { CTA } from "@/components/CTA";
import catalog from "@/data/legacy-catalog.json";
import { CatalogExplorer } from "@/components/CatalogExplorer";
export const metadata = { title: "Products" };
export default function Products(){return <><section className="bg-navy px-5 py-20 text-white"><div className="mx-auto max-w-7xl"><p className="eyebrow !text-blue-300">Product center</p><h1 className="text-5xl font-black">Valves & Piping Products</h1><p className="mt-5 max-w-2xl leading-8 text-white/65">Explore Dawei&apos;s valve-focused product range and supporting piping products. Search by product type, material, standard, or pressure class.</p><div className="mt-8 flex gap-8 text-sm"><p><b className="text-3xl text-signal">60+</b><br/>Valve product series</p><p><b className="text-3xl text-signal">API · ANSI · BS · DIN</b><br/>International standards</p></div></div></section><section className="px-5 py-16"><div className="mx-auto max-w-7xl"><div className="mb-10"><p className="eyebrow">Product categories</p><h2 className="section-title">Find products by application and type.</h2></div><div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{products.map(p=><Link href={`/products/${p.slug}`} key={p.slug} className="group overflow-hidden border border-slate-200 hover:border-valve hover:shadow-xl"><ProductVisual type={p.type} image={p.image} name={p.name} compact/><div className="p-6"><h2 className="text-xl font-black text-navy group-hover:text-valve">{p.name}</h2><p className="mt-3 text-sm leading-6 text-slate-500">{p.short}</p><span className="mt-5 flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-valve">Explore category <ArrowRight size={14}/></span></div></Link>)}</div></div></section><section className="border-t bg-mist px-5 py-16"><div className="mx-auto max-w-7xl"><div className="mb-10"><p className="eyebrow">All products</p><h2 className="section-title">Detailed product selection.</h2><p className="mt-4 max-w-2xl leading-7 text-slate-600">Review product configurations and technical information, then send your required specifications for confirmation and quotation.</p></div><CatalogExplorer products={catalog}/></div></section><CTA/></>}
